import {
  Body,
  Controller,
  Delete,
  Get,
  HttpCode,
  HttpStatus,
  NotFoundException,
  Param,
  ParseUUIDPipe,
  Patch,
  Post,
  Put,
  Query,
  UploadedFile,
  UseGuards,
  UseInterceptors,
} from '@nestjs/common';
import { FileInterceptor } from '@nestjs/platform-express';
import {
  ApiBadRequestResponse,
  ApiBearerAuth,
  ApiBody,
  ApiConsumes,
  ApiCreatedResponse,
  ApiForbiddenResponse,
  ApiNoContentResponse,
  ApiNotFoundResponse,
  ApiOkResponse,
  ApiOperation,
  ApiTags,
} from '@nestjs/swagger';
import { RolesGuard } from '../../common/guards/roles.guard';
import { Roles } from '../../common/decorators/roles.decorator';
import { Public } from '../../common/decorators/public.decorator';
import { OptionalAuthGuard } from '../../common/guards/optional-auth.guard';
import { GetUser } from '../../common/decorators/get-user.decorator';
import { SponsorshipService } from './sponsorship.service';
import { ProposalCopilotService } from './proposal-copilot.service';
import { CreateProposalDto } from './dto/create-proposal.dto';
import { UpdateProposalDto } from './dto/update-proposal.dto';
import { ListProposalsQueryDto } from './dto/list-proposals-query.dto';
import { ListPublishedQueryDto } from './dto/list-published-query.dto';
import { GenerateProposalDraftDto } from './dto/generate-proposal-draft.dto';
import { ListSponsorshipChatsQueryDto } from './dto/list-sponsorship-chats-query.dto';
import { SendChatMessageDto } from './dto/send-chat-message.dto';
import { UpdateChatMessageDto } from './dto/update-chat-message.dto';
import { UpsertSponsorshipDealDto } from './dto/upsert-sponsorship-deal.dto';
import { RequestDealChangesDto } from './dto/request-deal-changes.dto';
import { UpsertSponsorshipDealReportDto } from './dto/upsert-sponsorship-deal-report.dto';
import { VerifySponsorshipDealPaymentDto } from './dto/verify-sponsorship-deal-payment.dto';
import { SponsorshipInvoicePdfService } from './sponsorship-invoice-pdf.service';
import { SponsorshipReportPdfService } from './sponsorship-report-pdf.service';

@ApiTags('Sponsorship Proposals')
@ApiBearerAuth('firebase-token')
@Controller('sponsorships')
export class SponsorshipController {
  constructor(
    private readonly sponsorshipService: SponsorshipService,
    private readonly proposalCopilotService: ProposalCopilotService,
    private readonly sponsorshipInvoicePdfService: SponsorshipInvoicePdfService,
    private readonly sponsorshipReportPdfService: SponsorshipReportPdfService,
  ) {}

  @Post('copilot/generate-draft')
  @UseGuards(RolesGuard)
  @Roles('HOST')
  @ApiOperation({
    summary: 'Generate a sponsorship proposal draft using AI Copilot',
    description: 'Accepts a natural language prompt from the host and returns a fully structured sponsorship proposal draft generated by the Meetday AI Copilot.',
  })
  @ApiOkResponse({ description: 'AI-generated sponsorship proposal draft.' })
  @ApiForbiddenResponse({ description: 'Host role required.' })
  @ApiBadRequestResponse({ description: 'Prompt too short or too long.' })
  generateProposalDraft(
    @GetUser('uid') uid: string,
    @Body() dto: GenerateProposalDraftDto,
  ) {
    return this.proposalCopilotService.generateDraft(dto.prompt, uid);
  }

  @Post('copilot/extract-document')
  @UseGuards(RolesGuard)
  @Roles('HOST')
  @UseInterceptors(FileInterceptor('file', { limits: { fileSize: 10 * 1024 * 1024 } }))
  @ApiConsumes('multipart/form-data')
  @ApiBody({ schema: { type: 'object', properties: { file: { type: 'string', format: 'binary' } } } })
  @ApiOperation({
    summary: 'Extract text from an uploaded document for AI Copilot context',
    description: 'Accepts a PDF, DOCX, or PPTX file (e.g. an existing pitch deck) and returns its text so it can be combined with the Copilot prompt.',
  })
  @ApiOkResponse({ description: 'Extracted text.' })
  @ApiBadRequestResponse({ description: 'Unsupported file type or unreadable document.' })
  async extractCopilotDocument(@UploadedFile() file: { buffer: Buffer; originalname: string }) {
    const text = await this.proposalCopilotService.extractDocumentText(file.buffer, file.originalname);
    return { text };
  }

  @Post()
  @UseGuards(RolesGuard)
  @Roles('HOST')
  @HttpCode(HttpStatus.CREATED)
  @ApiOperation({
    summary: 'Create a new sponsorship proposal draft',
    description:
      'Creates a proposal in DRAFT status. All fields are optional — hosts can save partial data ' +
      'at any step. Use PATCH /sponsorships/:id to update, and PATCH /sponsorships/:id/submit ' +
      'when ready for admin review.',
  })
  @ApiCreatedResponse({ description: 'Proposal draft created.' })
  @ApiForbiddenResponse({ description: 'Host not approved.' })
  @ApiNotFoundResponse({ description: 'Host profile not found.' })
  createProposal(@GetUser('id') userId: string, @Body() dto: CreateProposalDto) {
    return this.sponsorshipService.createProposal(userId, dto);
  }

  @Get('me')
  @UseGuards(RolesGuard)
  @Roles('HOST')
  @ApiOperation({
    summary: "List host's own sponsorship proposals",
    description: "Returns the authenticated host's proposals. Filter by `status`.",
  })
  @ApiOkResponse({ description: 'List of proposals.' })
  getMyProposals(@GetUser('id') userId: string, @Query() query: ListProposalsQueryDto) {
    return this.sponsorshipService.getMyProposals(userId, query);
  }

  @Get('published')
  @Public()
  @UseGuards(OptionalAuthGuard)
  @ApiOperation({
    summary: 'List all published sponsorship proposals (data room — public preview)',
    description:
      'Returns every PUBLISHED proposal across all hosts, newest first. Pass `categoryId` to filter ' +
      "by the host's approved community profile category. Accessible without login for the public " +
      'data room link; full proposal detail still requires a BRAND account.',
  })
  @ApiOkResponse({ description: 'List of published proposals.' })
  getAllPublished(@Query() query: ListPublishedQueryDto) {
    return this.sponsorshipService.getAllPublishedProposals(query);
  }

  @Get('communities')
  @UseGuards(RolesGuard)
  @Roles('BRAND')
  @ApiOperation({
    summary: 'List onboarded communities (brand view)',
    description: 'Basic info (logo, name, size, categories) for admin-approved host community profiles.',
  })
  @ApiOkResponse({ description: 'List of onboarded communities.' })
  getCommunities() {
    return this.sponsorshipService.listApprovedCommunities();
  }

  @Get('published/:id')
  @Public()
  @UseGuards(OptionalAuthGuard)
  @ApiOperation({
    summary: 'Get a published sponsorship proposal detail (brand view)',
    description:
      "Full proposal detail plus the host's community profile. Accessible without login so a " +
      "host's shareable proposal link can render a preview before gating on brand sign-in.",
  })
  @ApiOkResponse({ description: 'Proposal detail with community profile.' })
  @ApiNotFoundResponse({ description: 'Proposal not found or not published.' })
  getPublishedDetail(@GetUser('id') userId: string | undefined, @Param('id', ParseUUIDPipe) id: string) {
    return this.sponsorshipService.getPublishedProposalDetail(id, userId);
  }

  @Post('published/:id/interest')
  @UseGuards(RolesGuard)
  @Roles('BRAND')
  @HttpCode(HttpStatus.CREATED)
  @ApiOperation({
    summary: 'Mark interest in a published sponsorship proposal',
    description:
      'Notifies admins (full brand details) and anonymously notifies the hosting community. ' +
      'Requires a complete brand profile (name, categories, social links). Idempotent.',
  })
  @ApiOkResponse({ description: 'Interest recorded.' })
  @ApiNotFoundResponse({ description: 'Proposal not found or not published.' })
  @ApiBadRequestResponse({ description: 'Brand profile is incomplete.' })
  markInterest(@GetUser('id') userId: string, @Param('id', ParseUUIDPipe) id: string) {
    return this.sponsorshipService.markInterest(userId, id);
  }

  // ── TriChat ──────────────────────────────────────────────────────────────
  // Registered before the generic ':id' route below so 'chats' isn't swallowed as a proposal id.

  @Get('chats')
  @UseGuards(RolesGuard)
  @Roles('HOST', 'BRAND')
  @ApiOperation({
    summary: 'List my sponsorship chat threads',
    description:
      'Host sees one thread per interested brand on their proposals; a brand sees one thread per ' +
      'proposal they expressed interest in. Filter by `status=REQUESTED` (not yet accepted) or ' +
      '`status=ACCEPTED` (chat open) — omit for both.',
  })
  @ApiOkResponse({ description: 'List of chat threads.' })
  listMyChats(@GetUser('id') userId: string, @Query() query: ListSponsorshipChatsQueryDto) {
    return this.sponsorshipService.listMyChats(userId, query);
  }

  @Get('chats/:interestId/messages')
  @UseGuards(RolesGuard)
  @Roles('HOST', 'BRAND')
  @ApiOperation({ summary: 'List messages in a chat thread' })
  @ApiOkResponse({ description: 'Messages, oldest first.' })
  @ApiForbiddenResponse({ description: 'Not a participant in this chat.' })
  @ApiNotFoundResponse({ description: 'Chat thread not found.' })
  listChatMessages(@GetUser('id') userId: string, @Param('interestId', ParseUUIDPipe) interestId: string) {
    return this.sponsorshipService.listChatMessages(userId, interestId);
  }

  @Post('chats/:interestId/messages')
  @UseGuards(RolesGuard)
  @Roles('HOST', 'BRAND')
  @HttpCode(HttpStatus.CREATED)
  @ApiOperation({
    summary: 'Send a chat message',
    description: 'Only allowed once the host has accepted the request (chatStatus=ACCEPTED).',
  })
  @ApiOkResponse({ description: 'Message sent.' })
  @ApiForbiddenResponse({ description: 'Not a participant in this chat.' })
  @ApiBadRequestResponse({ description: 'Request not yet accepted.' })
  sendChatMessage(
    @GetUser('id') userId: string,
    @Param('interestId', ParseUUIDPipe) interestId: string,
    @Body() dto: SendChatMessageDto,
  ) {
    return this.sponsorshipService.sendChatMessage(userId, interestId, dto);
  }

  @Patch('chats/:interestId/messages/:messageId')
  @UseGuards(RolesGuard)
  @Roles('HOST', 'BRAND')
  @ApiOperation({ summary: 'Edit a message you sent', description: 'Only the original sender can edit; adds an "edited" marker.' })
  @ApiOkResponse({ description: 'Message updated.' })
  @ApiForbiddenResponse({ description: 'Not your message.' })
  @ApiNotFoundResponse({ description: 'Message not found.' })
  editChatMessage(
    @GetUser('id') userId: string,
    @Param('interestId', ParseUUIDPipe) interestId: string,
    @Param('messageId', ParseUUIDPipe) messageId: string,
    @Body() dto: UpdateChatMessageDto,
  ) {
    return this.sponsorshipService.editChatMessage(userId, interestId, messageId, dto);
  }

  @Delete('chats/:interestId/messages/:messageId')
  @UseGuards(RolesGuard)
  @Roles('HOST', 'BRAND')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Delete a message you sent',
    description: 'Soft delete — shows a placeholder to both sides, but admins can still see the original content.',
  })
  @ApiOkResponse({ description: 'Message deleted.' })
  @ApiForbiddenResponse({ description: 'Not your message.' })
  @ApiNotFoundResponse({ description: 'Message not found.' })
  deleteChatMessage(
    @GetUser('id') userId: string,
    @Param('interestId', ParseUUIDPipe) interestId: string,
    @Param('messageId', ParseUUIDPipe) messageId: string,
  ) {
    return this.sponsorshipService.deleteChatMessage(userId, interestId, messageId);
  }

  @Post('chats/:interestId/accept')
  @UseGuards(RolesGuard)
  @Roles('HOST')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: "Accept a brand's interest and open the chat",
    description: 'Moves the thread from "Requests" to "General"/"Accepted" on both sides.',
  })
  @ApiOkResponse({ description: 'Request accepted.' })
  @ApiForbiddenResponse({ description: 'Not the host who owns this proposal.' })
  @ApiNotFoundResponse({ description: 'Chat thread not found.' })
  acceptChatRequest(@GetUser('id') userId: string, @Param('interestId', ParseUUIDPipe) interestId: string) {
    return this.sponsorshipService.acceptChatRequest(userId, interestId);
  }

  // ── Deal Lock ────────────────────────────────────────────────────────────

  @Get('chats/:interestId/deal')
  @UseGuards(RolesGuard)
  @Roles('HOST', 'BRAND')
  @ApiOperation({ summary: 'Get the negotiated deal for a chat thread, if one exists' })
  @ApiOkResponse({ description: 'Deal, or null if none has been locked/proposed yet.' })
  @ApiForbiddenResponse({ description: 'Not a participant in this chat.' })
  getDeal(@GetUser('id') userId: string, @Param('interestId', ParseUUIDPipe) interestId: string) {
    return this.sponsorshipService.getDeal(userId, interestId);
  }

  @Post('chats/:interestId/deal')
  @UseGuards(RolesGuard)
  @Roles('HOST')
  @HttpCode(HttpStatus.CREATED)
  @ApiOperation({
    summary: 'Lock the deal — community submits the final negotiated terms',
    description: 'Only the community can do this, and only once per chat — use PATCH to edit afterwards.',
  })
  @ApiOkResponse({ description: 'Deal created.' })
  @ApiForbiddenResponse({ description: 'Not the host, or chat not yet accepted.' })
  @ApiBadRequestResponse({ description: 'A deal already exists for this chat.' })
  createDeal(
    @GetUser('id') userId: string,
    @Param('interestId', ParseUUIDPipe) interestId: string,
    @Body() dto: UpsertSponsorshipDealDto,
  ) {
    return this.sponsorshipService.createDeal(userId, interestId, dto);
  }

  @Patch('chats/:interestId/deal')
  @UseGuards(RolesGuard)
  @Roles('HOST')
  @ApiOperation({
    summary: 'Edit the deal',
    description: 'Resets status to PENDING_APPROVAL and bumps the version. Not allowed once APPROVED.',
  })
  @ApiOkResponse({ description: 'Deal updated.' })
  @ApiNotFoundResponse({ description: 'No deal exists yet for this chat.' })
  @ApiBadRequestResponse({ description: 'Deal is already locked/approved.' })
  updateDeal(
    @GetUser('id') userId: string,
    @Param('interestId', ParseUUIDPipe) interestId: string,
    @Body() dto: UpsertSponsorshipDealDto,
  ) {
    return this.sponsorshipService.updateDeal(userId, interestId, dto);
  }

  @Post('chats/:interestId/deal/approve')
  @UseGuards(RolesGuard)
  @Roles('BRAND')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Approve and lock the deal — brand only' })
  @ApiOkResponse({ description: 'Deal locked.' })
  @ApiNotFoundResponse({ description: 'No deal exists yet for this chat.' })
  approveDeal(@GetUser('id') userId: string, @Param('interestId', ParseUUIDPipe) interestId: string) {
    return this.sponsorshipService.approveDeal(userId, interestId);
  }

  @Post('chats/:interestId/deal/request-changes')
  @UseGuards(RolesGuard)
  @Roles('BRAND')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Request changes to the proposed deal — brand only' })
  @ApiOkResponse({ description: 'Deal marked as changes requested.' })
  @ApiNotFoundResponse({ description: 'No deal exists yet for this chat.' })
  @ApiBadRequestResponse({ description: 'Deal is already locked/approved.' })
  requestDealChanges(
    @GetUser('id') userId: string,
    @Param('interestId', ParseUUIDPipe) interestId: string,
    @Body() dto: RequestDealChangesDto,
  ) {
    return this.sponsorshipService.requestDealChanges(userId, interestId, dto);
  }

  @Get('chats/:interestId/deal/report')
  @UseGuards(RolesGuard)
  @Roles('HOST', 'BRAND')
  @ApiOperation({ summary: 'Get the submitted deliverables report for a locked deal, if any' })
  @ApiOkResponse({ description: 'Report, or null if none has been submitted yet.' })
  @ApiNotFoundResponse({ description: 'No deal exists yet for this chat.' })
  getDealReport(@GetUser('id') userId: string, @Param('interestId', ParseUUIDPipe) interestId: string) {
    return this.sponsorshipService.getDealReport(userId, interestId);
  }

  @Put('chats/:interestId/deal/report')
  @UseGuards(RolesGuard)
  @Roles('HOST', 'BRAND')
  @ApiOperation({
    summary: 'Submit/resubmit the deliverables report (community), or approve / request revision (brand)',
    description: 'Only enabled once the deal is APPROVED/locked. Brand can only act on an already-submitted report.',
  })
  @ApiOkResponse({ description: 'Report saved.' })
  @ApiNotFoundResponse({ description: 'No deal exists yet for this chat.' })
  @ApiBadRequestResponse({ description: 'Deal is not yet locked/approved.' })
  upsertDealReport(
    @GetUser('id') userId: string,
    @Param('interestId', ParseUUIDPipe) interestId: string,
    @Body() dto: UpsertSponsorshipDealReportDto,
  ) {
    return this.sponsorshipService.upsertDealReport(userId, interestId, dto);
  }

  @Post('chats/:interestId/deal/payment/initiate')
  @UseGuards(RolesGuard)
  @Roles('BRAND')
  @ApiOperation({ summary: 'Create a Razorpay order to pay for a locked deal — brand only' })
  @ApiOkResponse({ description: 'Razorpay order details for the checkout widget.' })
  @ApiNotFoundResponse({ description: 'No deal exists yet for this chat.' })
  @ApiBadRequestResponse({ description: 'Deal is not locked, or already paid.' })
  initiateDealPayment(@GetUser('id') userId: string, @Param('interestId', ParseUUIDPipe) interestId: string) {
    return this.sponsorshipService.initiateDealPayment(userId, interestId);
  }

  @Post('chats/:interestId/deal/payment/verify')
  @UseGuards(RolesGuard)
  @Roles('BRAND')
  @ApiOperation({ summary: 'Verify a completed Razorpay payment for a locked deal — brand only' })
  @ApiOkResponse({ description: 'Deal marked as paid.' })
  @ApiNotFoundResponse({ description: 'No deal exists yet for this chat.' })
  @ApiForbiddenResponse({ description: 'Invalid payment signature.' })
  verifyDealPayment(
    @GetUser('id') userId: string,
    @Param('interestId', ParseUUIDPipe) interestId: string,
    @Body() dto: VerifySponsorshipDealPaymentDto,
  ) {
    return this.sponsorshipService.verifyDealPayment(userId, interestId, dto);
  }

  @Get('billing')
  @UseGuards(RolesGuard)
  @Roles('BRAND')
  @ApiOperation({ summary: 'List all locked deals for the brand, with payment breakdown and status — brand only' })
  @ApiOkResponse({ description: 'List of locked deals across all chats.' })
  listBrandDealsBilling(@GetUser('id') userId: string) {
    return this.sponsorshipService.listBrandDealsBilling(userId);
  }

  @Get('chats/:interestId/deal/invoice')
  @UseGuards(RolesGuard)
  @Roles('HOST', 'BRAND')
  @ApiOperation({ summary: 'Get a presigned download URL for the paid deal\'s receipt PDF' })
  @ApiOkResponse({ description: 'Presigned invoice PDF URL.' })
  @ApiNotFoundResponse({ description: 'No deal exists, or it has not been paid for yet.' })
  async getDealInvoiceUrl(@GetUser('id') userId: string, @Param('interestId', ParseUUIDPipe) interestId: string) {
    const deal = await this.sponsorshipService.getDeal(userId, interestId);
    if (!deal || deal.paymentStatus !== 'PAID') throw new NotFoundException('No paid deal found for this chat');
    const url = await this.sponsorshipInvoicePdfService.getDownloadUrl(deal.id);
    return { url };
  }

  @Get('chats/:interestId/deal/report/pdf')
  @UseGuards(RolesGuard)
  @Roles('HOST', 'BRAND')
  @ApiOperation({ summary: 'Get a presigned download URL for the deliverables report as a PDF' })
  @ApiOkResponse({ description: 'Presigned report PDF URL.' })
  @ApiNotFoundResponse({ description: 'No report has been submitted for this deal yet.' })
  async getDealReportPdfUrl(@GetUser('id') userId: string, @Param('interestId', ParseUUIDPipe) interestId: string) {
    // Reuses getDeal's participant access check before generating the PDF.
    await this.sponsorshipService.getDeal(userId, interestId);
    const url = await this.sponsorshipReportPdfService.getDownloadUrl(interestId);
    return { url };
  }

  @Get(':id')
  @UseGuards(RolesGuard)
  @Roles('HOST')
  @ApiOperation({ summary: 'Get own proposal detail' })
  @ApiOkResponse({ description: 'Proposal detail.' })
  @ApiNotFoundResponse({ description: 'Proposal not found.' })
  @ApiForbiddenResponse({ description: 'Not the owner.' })
  getProposalDetail(@GetUser('id') userId: string, @Param('id', ParseUUIDPipe) id: string) {
    return this.sponsorshipService.getProposalDetail(userId, id);
  }

  @Patch(':id')
  @UseGuards(RolesGuard)
  @Roles('HOST')
  @ApiOperation({
    summary: 'Update a sponsorship proposal',
    description:
      'DRAFT/REJECTED proposals are updated directly. UNDER_REVIEW/PUBLISHED proposals stash the ' +
      'edits as a pending revision awaiting admin approval — the live/submitted version is untouched.',
  })
  @ApiOkResponse({ description: 'Proposal updated (or revision saved).' })
  @ApiNotFoundResponse({ description: 'Proposal not found.' })
  @ApiForbiddenResponse({ description: 'Not the owner.' })
  @ApiBadRequestResponse({ description: 'No changes provided.' })
  updateProposal(
    @GetUser('id') userId: string,
    @Param('id', ParseUUIDPipe) id: string,
    @Body() dto: UpdateProposalDto,
  ) {
    return this.sponsorshipService.updateProposal(userId, id, dto);
  }

  @Patch(':id/submit')
  @UseGuards(RolesGuard)
  @Roles('HOST')
  @ApiOperation({
    summary: 'Submit a proposal for admin review',
    description:
      'Validates all required fields are populated, then moves the proposal to UNDER_REVIEW. ' +
      'Returns a 400 with the list of missing fields if incomplete. Requires an admin-approved ' +
      'community profile (POST /hosts/community) first.',
  })
  @ApiOkResponse({ description: 'Proposal submitted for review.' })
  @ApiForbiddenResponse({ description: 'Not the owner, or proposal is not DRAFT/REJECTED.' })
  @ApiNotFoundResponse({ description: 'Proposal not found.' })
  @ApiBadRequestResponse({
    description: 'Proposal is incomplete, or the community profile is not yet admin-approved.',
  })
  submitProposal(@GetUser('id') userId: string, @Param('id', ParseUUIDPipe) id: string) {
    return this.sponsorshipService.submitProposal(userId, id);
  }

  @Delete(':id')
  @UseGuards(RolesGuard)
  @Roles('HOST')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Delete a sponsorship proposal',
    description: 'Permanently deletes any sponsorship proposal owned by the host.',
  })
  @ApiOkResponse({ description: 'Proposal deleted successfully.' })
  @ApiForbiddenResponse({ description: 'Not the owner.' })
  @ApiNotFoundResponse({ description: 'Proposal not found.' })
  deleteProposal(@GetUser('id') userId: string, @Param('id', ParseUUIDPipe) id: string) {
    return this.sponsorshipService.deleteProposal(userId, id);
  }
}
