stages:
  - build

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_BUILDKIT: "1"
  IMAGE: $CI_REGISTRY_IMAGE

build-dev:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - docker builder prune -f
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build
        -t $IMAGE:dev
        -t $IMAGE:$CI_COMMIT_SHORT_SHA
        .
    - docker push $IMAGE:dev
    - docker push $IMAGE:$CI_COMMIT_SHORT_SHA
  after_script:
    - docker builder prune -f
    - docker image prune -f
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
