import {
  Body,
  Controller,
  Delete,
  Get,
  HttpCode,
  HttpStatus,
  Param,
  ParseUUIDPipe,
  Patch,
  Post,
  UploadedFile,
  UseGuards,
  UseInterceptors,
} from '@nestjs/common';
import { FileInterceptor } from '@nestjs/platform-express';
import {
  ApiBearerAuth,
  ApiBadRequestResponse,
  ApiBody,
  ApiConsumes,
  ApiCreatedResponse,
  ApiOkResponse,
  ApiOperation,
  ApiTags,
} from '@nestjs/swagger';
import { RolesGuard } from '../../common/guards/roles.guard';
import { Roles } from '../../common/decorators/roles.decorator';
import { GetUser } from '../../common/decorators/get-user.decorator';
import { CampaignsService } from './campaigns.service';
import { CampaignCopilotService } from './campaign-copilot.service';
import { DocumentExtractionService } from '../../common/document-extraction/document-extraction.service';
import { CreateCampaignDto } from './dto/create-campaign.dto';
import { UpdateCampaignDto } from './dto/update-campaign.dto';
import { GenerateCampaignDraftDto } from './dto/generate-campaign-draft.dto';

@ApiTags('Campaigns')
@ApiBearerAuth('firebase-token')
@UseGuards(RolesGuard)
@Roles('BRAND')
@Controller('campaigns')
export class CampaignsController {
  constructor(
    private readonly campaignsService: CampaignsService,
    private readonly campaignCopilotService: CampaignCopilotService,
    private readonly documentExtractionService: DocumentExtractionService,
  ) {}

  @Post('copilot/generate-draft')
  @ApiOperation({
    summary: 'Generate a campaign draft using AI Copilot',
    description: 'Accepts a natural language prompt from the brand and returns a fully structured campaign draft generated by the Meetday AI Copilot.',
  })
  @ApiOkResponse({ description: 'AI-generated campaign draft.' })
  @ApiBadRequestResponse({ description: 'Prompt too short or too long.' })
  generateCampaignDraft(
    @GetUser('id') userId: string,
    @Body() dto: GenerateCampaignDraftDto,
  ) {
    return this.campaignCopilotService.generateDraft(dto.prompt, userId);
  }

  @Post('copilot/extract-document')
  @UseInterceptors(FileInterceptor('file', { limits: { fileSize: 10 * 1024 * 1024 } }))
  @ApiConsumes('multipart/form-data')
  @ApiBody({ schema: { type: 'object', properties: { file: { type: 'string', format: 'binary' } } } })
  @ApiOperation({
    summary: 'Extract text from an uploaded document for AI Copilot context',
    description: 'Accepts a PDF, DOCX, or PPTX file and returns its text so it can be combined with the Copilot prompt.',
  })
  @ApiOkResponse({ description: 'Extracted text.' })
  @ApiBadRequestResponse({ description: 'Unsupported file type or unreadable document.' })
  async extractCopilotDocument(@UploadedFile() file: { buffer: Buffer; originalname: string }) {
    const text = await this.documentExtractionService.extractText(file.buffer, file.originalname);
    return { text };
  }

  @Post()
  @HttpCode(HttpStatus.CREATED)
  @ApiOperation({ summary: 'Create a new campaign brief' })
  @ApiCreatedResponse({ description: 'Campaign brief created.' })
  createCampaign(
    @GetUser('id') userId: string,
    @Body() dto: CreateCampaignDto,
  ) {
    return this.campaignsService.createCampaign(userId, dto);
  }

  @Get('published')
  @Roles('HOST', 'BRAND')
  @ApiOperation({ summary: 'List all published campaigns' })
  @ApiOkResponse({ description: 'List of published campaigns.' })
  getPublishedCampaigns() {
    return this.campaignsService.getPublishedCampaigns();
  }

  @Get('published/:id')
  @Roles('HOST', 'BRAND')
  @ApiOperation({ summary: 'Get details of a published campaign' })
  @ApiOkResponse({ description: 'Campaign details.' })
  getPublishedCampaign(@Param('id', ParseUUIDPipe) campaignId: string) {
    return this.campaignsService.getPublishedCampaign(campaignId);
  }

  @Get()
  @ApiOperation({ summary: "List brand's own campaigns" })
  @ApiOkResponse({ description: 'List of campaigns.' })
  getCampaigns(@GetUser('id') userId: string) {
    return this.campaignsService.getCampaigns(userId);
  }

  @Get(':id')
  @ApiOperation({ summary: 'Get details of a campaign' })
  @ApiOkResponse({ description: 'Campaign details.' })
  getCampaign(
    @GetUser('id') userId: string,
    @Param('id', ParseUUIDPipe) campaignId: string,
  ) {
    return this.campaignsService.getCampaign(userId, campaignId);
  }

  @Patch(':id')
  @ApiOperation({ summary: 'Update an existing campaign' })
  @ApiOkResponse({ description: 'Updated campaign details.' })
  updateCampaign(
    @GetUser('id') userId: string,
    @Param('id', ParseUUIDPipe) campaignId: string,
    @Body() dto: UpdateCampaignDto,
  ) {
    return this.campaignsService.updateCampaign(userId, campaignId, dto);
  }

  @Delete(':id')
  @ApiOperation({ summary: 'Delete a campaign brief' })
  @ApiOkResponse({ description: 'Campaign deleted.' })
  deleteCampaign(
    @GetUser('id') userId: string,
    @Param('id', ParseUUIDPipe) campaignId: string,
  ) {
    return this.campaignsService.deleteCampaign(userId, campaignId);
  }
}
